name: dot_node
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  get:
  validators:
  flutter_screenutil:
  # riverpod
  flutter_riverpod: ^2.3.6
  
  flutter_secure_storage:
  logger:
  image_picker:

  # google auth,icon
  google_sign_in: ^6.1.4
  font_awesome_flutter: ^10.5.0
  #firebase, google auth 
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_auth_platform_interface: ^6.16.0
 



  cupertino_icons: ^1.0.2

dev_dependencies:
  http:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

platforms:
  web:
    assets:
      - assets/
