name: Dot node Action

on:
  push:
    branches: [ master, feature, dev ]
  pull_request:
    branches: [ master, feature, dev ]

jobs:
  build:
    name: Running CI/CD
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Import Flutter Package
        run: |
          flutter pub get      
      # 다섯번째 step은 작성된 코드를 build 하는 단계입니다.
      # 빌드 후 빌드 된 파일을 프로젝트 루트로 옮기겠습니다.
      # 옮기는 이유 : .gitignore에 build 폴더가 정의되어 있어
      # 추후 사용 불가. 따로 커밋을 하지 않는 이상 
      # 여기서 변경된 사항은 프로젝트에 영향을 주지 않습니다.
      # 이미 web이라는 폴더가 존재하여 web_deploy으로 이름을 변경합니다.
      - name: Build Flutter web
        run: |
          flutter build web --release
          mv ./build/web .
          
